 project = "kpmg"
 region = "us-central1"
 zone = "us-central1-a"
 server_name = "apache-server"
 machinetype = "f1-micro"
 bucket_name = "appengine-static-content"
 sql_name = "master-db"
 db_name = "database01"